-- Migration 100: Family-level automatic weekend and public-holiday reward sales.
-- Holiday dates are generated by the admin client from date-holidays using only
-- its `public` classification. Checkout remains server-authoritative.

create or replace function public.admin_update_automatic_sale(p_config jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id uuid := public.assert_parent_admin();
  v_percentage integer;
  v_timezone text;
  v_date text;
  v_normalized jsonb;
begin
  if p_config is null or jsonb_typeof(p_config) <> 'object' then
    raise exception 'Automatic sale config must be an object';
  end if;

  if coalesce(p_config->>'percentage', '') !~ '^\d{1,3}$' then
    raise exception 'Sale percentage must be a whole number from 0 to 100';
  end if;
  v_percentage := (p_config->>'percentage')::integer;
  if v_percentage < 0 or v_percentage > 100 then
    raise exception 'Sale percentage must be between 0 and 100';
  end if;

  v_timezone := nullif(trim(p_config->>'timezone'), '');
  if v_timezone is null or not exists (
    select 1 from pg_catalog.pg_timezone_names where name = v_timezone
  ) then
    raise exception 'Invalid sale timezone';
  end if;

  if jsonb_typeof(coalesce(p_config->'holidayDates', '[]'::jsonb)) <> 'array' then
    raise exception 'Holiday dates must be an array';
  end if;
  for v_date in
    select value from jsonb_array_elements_text(coalesce(p_config->'holidayDates', '[]'::jsonb))
  loop
    if v_date !~ '^\d{4}-\d{2}-\d{2}$' then
      raise exception 'Invalid holiday date: %', v_date;
    end if;
    perform v_date::date;
  end loop;

  v_normalized := jsonb_build_object(
    'weekendEnabled', coalesce((p_config->>'weekendEnabled')::boolean, false),
    'holidayEnabled', coalesce((p_config->>'holidayEnabled')::boolean, false),
    'percentage', v_percentage,
    'countryCode', left(coalesce(nullif(trim(p_config->>'countryCode'), ''), 'CA'), 8),
    'subdivisionCode', left(coalesce(trim(p_config->>'subdivisionCode'), ''), 16),
    'timezone', v_timezone,
    'holidayDates', coalesce(p_config->'holidayDates', '[]'::jsonb),
    'generatedThrough', greatest(coalesce((p_config->>'generatedThrough')::integer, 0), 0)
  );

  insert into public.family_settings (key, value, updated_at, family_id)
  values ('automatic_reward_sale', v_normalized::text, now(), v_family_id)
  on conflict (key, family_id) do update
    set value = excluded.value,
        updated_at = excluded.updated_at;
end;
$$;

revoke all on function public.admin_update_automatic_sale(jsonb) from public, anon;
grant execute on function public.admin_update_automatic_sale(jsonb) to authenticated;

create or replace function public.automatic_reward_sale_context(
  p_family_id uuid,
  p_at timestamptz default now()
)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_config jsonb;
  v_timezone text;
  v_local timestamp;
  v_date text;
  v_weekend boolean := false;
  v_holiday boolean := false;
  v_percentage integer := 0;
  v_reason text := null;
begin
  begin
    select value::jsonb into v_config
    from public.family_settings
    where family_id = p_family_id
      and key = 'automatic_reward_sale'
    limit 1;
  exception when others then
    v_config := null;
  end;

  if v_config is null or jsonb_typeof(v_config) <> 'object' then
    return jsonb_build_object('active', false, 'percentage', 0, 'reason', null, 'localDate', null);
  end if;

  v_timezone := coalesce(nullif(v_config->>'timezone', ''), 'UTC');
  if not exists (select 1 from pg_catalog.pg_timezone_names where name = v_timezone) then
    v_timezone := 'UTC';
  end if;
  v_local := timezone(v_timezone, coalesce(p_at, now()));
  v_date := to_char(v_local, 'YYYY-MM-DD');
  v_percentage := least(100, greatest(0, coalesce((v_config->>'percentage')::integer, 0)));
  v_weekend := coalesce((v_config->>'weekendEnabled')::boolean, false)
    and extract(isodow from v_local) in (6, 7);
  v_holiday := coalesce((v_config->>'holidayEnabled')::boolean, false)
    and coalesce(v_config->'holidayDates', '[]'::jsonb) ? v_date;

  v_reason := case
    when v_weekend and v_holiday then 'weekend_holiday'
    when v_holiday then 'holiday'
    when v_weekend then 'weekend'
    else null
  end;

  return jsonb_build_object(
    'active', v_reason is not null and v_percentage > 0,
    'percentage', case when v_reason is null then 0 else v_percentage end,
    'reason', v_reason,
    'localDate', v_date
  );
exception when others then
  return jsonb_build_object('active', false, 'percentage', 0, 'reason', null, 'localDate', null);
end;
$$;

revoke all on function public.automatic_reward_sale_context(uuid, timestamptz) from public, anon, authenticated;

create or replace function public.redeem_reward_atomic(
  p_user_id text,
  p_reward_id text,
  p_day_key text,
  p_now timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id uuid := public.get_my_family_id();
  v_level public.levels;
  v_reward public.rewards;
  v_base_cost integer;
  v_sale_percentage integer;
  v_sale_price integer;
  v_manual_cost integer;
  v_auto_context jsonb;
  v_auto_percentage integer := 0;
  v_auto_cost integer;
  v_current_cost integer;
  v_effective_sale_percentage integer;
  v_effective_sale_price integer;
  v_effective_sale_name text;
  v_new_balance integer;
  v_now timestamptz := coalesce(p_now, now());
begin
  if v_family_id is null then
    raise exception 'No family found for current user';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'redeem:' || v_family_id::text || ':' || p_user_id || ':' || p_reward_id,
    0
  ));

  if not exists (
    select 1 from public.users
    where id = p_user_id and family_id = v_family_id and deleted_at is null
  ) then
    raise exception 'User % not found', p_user_id;
  end if;

  select * into v_reward
  from public.rewards
  where id = p_reward_id::uuid and family_id = v_family_id
  for update;

  if not found then raise exception 'Reward % not found', p_reward_id; end if;
  if coalesce(v_reward.is_hidden, false) then raise exception 'Reward is not available'; end if;
  if coalesce(v_reward.is_sold_out, false) then raise exception '품절된 보상입니다'; end if;

  insert into public.levels (user_id, current_level, total_points, spendable_balance, updated_at)
  values (p_user_id, 1, 0, 0, v_now)
  on conflict (user_id) do nothing;

  select * into v_level from public.levels where user_id = p_user_id for update;

  v_base_cost := greatest(coalesce(v_reward.cost_points, 0), 0);
  v_sale_percentage := case when coalesce(v_reward.sale_enabled, false)
    then least(100, greatest(0, coalesce(v_reward.sale_percentage, 0))) else 0 end;
  v_sale_price := case
    when coalesce(v_reward.sale_enabled, false) and v_reward.sale_price is not null
      then least(v_base_cost, greatest(0, v_reward.sale_price))
    else null end;
  v_manual_cost := coalesce(
    v_sale_price,
    greatest(floor(v_base_cost - (v_base_cost * v_sale_percentage / 100.0))::integer, 0)
  );

  v_auto_context := public.automatic_reward_sale_context(v_family_id, v_now);
  if coalesce((v_auto_context->>'active')::boolean, false) then
    v_auto_percentage := least(100, greatest(0, coalesce((v_auto_context->>'percentage')::integer, 0)));
  end if;
  v_auto_cost := greatest(floor(v_base_cost - (v_base_cost * v_auto_percentage / 100.0))::integer, 0);
  v_current_cost := least(v_manual_cost, v_auto_cost);

  if v_auto_cost < v_manual_cost then
    v_effective_sale_percentage := v_auto_percentage;
    v_effective_sale_price := null;
    v_effective_sale_name := case v_auto_context->>'reason'
      when 'holiday' then 'Holiday Sale'
      when 'weekend_holiday' then 'Holiday Weekend Sale'
      else 'Weekend Sale' end;
  else
    v_effective_sale_percentage := v_sale_percentage;
    v_effective_sale_price := v_sale_price;
    v_effective_sale_name := v_reward.sale_name;
  end if;

  if exists (
    select 1 from public.reward_redemptions rr
    where rr.user_id = p_user_id
      and rr.reward_id = p_reward_id::uuid
      and coalesce(rr.is_joint_purchase, false) = false
      and rr.refunded_at is null
      and rr.redeemed_at >= v_now - interval '3 seconds'
  ) then
    raise exception '이미 처리된 구매입니다. 잠시 후 다시 시도해주세요.';
  end if;

  if coalesce(v_level.spendable_balance, 0) < v_current_cost then
    raise exception '잔액이 부족합니다';
  end if;

  v_new_balance := greatest(coalesce(v_level.spendable_balance, 0) - v_current_cost, 0);
  update public.levels
  set spendable_balance = v_new_balance, updated_at = v_now
  where user_id = p_user_id;

  insert into public.reward_redemptions (id, user_id, reward_id, redeemed_at, cost_charged)
  values (gen_random_uuid(), p_user_id, p_reward_id::uuid, v_now, v_current_cost);

  return jsonb_build_object(
    'spendableBalance', v_new_balance,
    'costCharged', v_current_cost,
    'baseCost', v_base_cost,
    'salePercentage', v_effective_sale_percentage,
    'salePrice', v_effective_sale_price,
    'saleName', v_effective_sale_name,
    'automaticSaleReason', v_auto_context->>'reason',
    'rewardId', p_reward_id
  );
end;
$$;

revoke all on function public.redeem_reward_atomic(text, text, text, timestamptz) from public, anon;
grant execute on function public.redeem_reward_atomic(text, text, text, timestamptz) to authenticated;

create or replace function public.purchase_reward_joint(
  p_reward_id text,
  p_user1_id text,
  p_user1_amount int,
  p_user2_id text,
  p_user2_amount int
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_family_id uuid := public.get_my_family_id();
  v_reward public.rewards;
  v_user1_level public.levels;
  v_user2_level public.levels;
  v_base_cost integer;
  v_sale_percentage integer;
  v_sale_price integer;
  v_manual_cost integer;
  v_auto_context jsonb;
  v_auto_percentage integer := 0;
  v_auto_cost integer;
  v_current_cost integer;
  v_user1_balance integer;
  v_user2_balance integer;
  v_redemption_id uuid := gen_random_uuid();
  v_uuid_pattern text := '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
  v_pair_key text;
  v_now timestamptz := now();
begin
  if v_family_id is null then raise exception 'No family found for current user'; end if;
  if p_reward_id !~* v_uuid_pattern or p_user1_id !~* v_uuid_pattern or p_user2_id !~* v_uuid_pattern then
    raise exception 'Joint purchase requires UUID reward and member IDs';
  end if;
  if p_user1_id = p_user2_id then raise exception 'Joint purchase requires two different users'; end if;

  v_pair_key := least(p_user1_id, p_user2_id) || ':' || greatest(p_user1_id, p_user2_id);
  perform pg_advisory_xact_lock(hashtextextended(
    'joint-redeem:' || v_family_id::text || ':' || p_reward_id || ':' || v_pair_key, 0
  ));

  if coalesce(p_user1_amount, 0) < 0 or coalesce(p_user2_amount, 0) < 0 then
    raise exception 'Payment amounts cannot be negative';
  end if;
  if not exists (select 1 from public.users where id = p_user1_id and family_id = v_family_id and deleted_at is null) then
    raise exception 'User 1 not found';
  end if;
  if not exists (select 1 from public.users where id = p_user2_id and family_id = v_family_id and deleted_at is null) then
    raise exception 'User 2 not found';
  end if;

  select * into v_reward from public.rewards
  where id = p_reward_id::uuid and family_id = v_family_id
  for update;
  if not found then raise exception 'Reward not found'; end if;
  if coalesce(v_reward.is_hidden, false) then raise exception 'Reward is not available'; end if;
  if coalesce(v_reward.is_sold_out, false) then raise exception '품절된 보상입니다'; end if;

  v_base_cost := greatest(coalesce(v_reward.cost_points, 0), 0);
  v_sale_percentage := case when coalesce(v_reward.sale_enabled, false)
    then least(100, greatest(0, coalesce(v_reward.sale_percentage, 0))) else 0 end;
  v_sale_price := case
    when coalesce(v_reward.sale_enabled, false) and v_reward.sale_price is not null
      then least(v_base_cost, greatest(0, v_reward.sale_price))
    else null end;
  v_manual_cost := coalesce(
    v_sale_price,
    greatest(floor(v_base_cost - (v_base_cost * v_sale_percentage / 100.0))::integer, 0)
  );
  v_auto_context := public.automatic_reward_sale_context(v_family_id, v_now);
  if coalesce((v_auto_context->>'active')::boolean, false) then
    v_auto_percentage := least(100, greatest(0, coalesce((v_auto_context->>'percentage')::integer, 0)));
  end if;
  v_auto_cost := greatest(floor(v_base_cost - (v_base_cost * v_auto_percentage / 100.0))::integer, 0);
  v_current_cost := least(v_manual_cost, v_auto_cost);

  if coalesce(p_user1_amount, 0) + coalesce(p_user2_amount, 0) <> v_current_cost then
    raise exception 'Split amounts must equal reward cost';
  end if;
  if exists (
    select 1 from public.reward_redemptions rr
    where rr.reward_id = p_reward_id::uuid
      and coalesce(rr.is_joint_purchase, false) = true
      and rr.refunded_at is null
      and rr.redeemed_at >= v_now - interval '3 seconds'
      and ((rr.joint_user1_id = p_user1_id::uuid and rr.joint_user2_id = p_user2_id::uuid)
        or (rr.joint_user1_id = p_user2_id::uuid and rr.joint_user2_id = p_user1_id::uuid))
  ) then
    raise exception '이미 처리된 구매입니다. 잠시 후 다시 시도해주세요.';
  end if;

  insert into public.levels (user_id, current_level, total_points, spendable_balance, updated_at)
  values (p_user1_id, 1, 0, 0, v_now), (p_user2_id, 1, 0, 0, v_now)
  on conflict (user_id) do nothing;

  select * into v_user1_level from public.levels where user_id = p_user1_id for update;
  select * into v_user2_level from public.levels where user_id = p_user2_id for update;
  if coalesce(v_user1_level.spendable_balance, 0) < p_user1_amount then
    raise exception '첫 번째 사용자의 잔액이 부족합니다';
  end if;
  if coalesce(v_user2_level.spendable_balance, 0) < p_user2_amount then
    raise exception '두 번째 사용자의 잔액이 부족합니다';
  end if;

  update public.levels
  set spendable_balance = coalesce(spendable_balance, 0) - p_user1_amount, updated_at = v_now
  where user_id = p_user1_id returning spendable_balance into v_user1_balance;
  update public.levels
  set spendable_balance = coalesce(spendable_balance, 0) - p_user2_amount, updated_at = v_now
  where user_id = p_user2_id returning spendable_balance into v_user2_balance;

  insert into public.reward_redemptions (
    id, user_id, reward_id, redeemed_at, cost_charged, is_joint_purchase,
    joint_user1_id, joint_user1_amount, joint_user2_id, joint_user2_amount
  ) values (
    v_redemption_id, p_user1_id::uuid, p_reward_id::uuid, v_now, v_current_cost, true,
    p_user1_id::uuid, p_user1_amount, p_user2_id::uuid, p_user2_amount
  );

  return jsonb_build_object(
    'redemptionId', v_redemption_id::text,
    'rewardId', p_reward_id,
    'costCharged', v_current_cost,
    'automaticSaleReason', v_auto_context->>'reason',
    'user1Id', p_user1_id,
    'user1Balance', v_user1_balance,
    'user2Id', p_user2_id,
    'user2Balance', v_user2_balance
  );
end;
$$;

revoke all on function public.purchase_reward_joint(text, text, int, text, int) from public, anon;
grant execute on function public.purchase_reward_joint(text, text, int, text, int) to authenticated;
